// Package dashboards tests the Grafana dashboards in grafana-dashboards/.
//
// Every panel query becomes a Prometheus recording rule in
// grafana-dashboards/test/queries.yml (dashboard variables replaced by fixed
// values), and grafana-dashboards/test/dashboards_test.yml checks the results
// with promtool against known data:
//
//	go test ./internal/dashboards -update   # after changing a dashboard
//	cd grafana-dashboards/test && promtool test rules dashboards_test.yml
package dashboards

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"testing"
)

var update = flag.Bool("update", false, "rewrite grafana-dashboards/test/queries.yml from the dashboards")

const (
	dashboardDir = "../../grafana-dashboards"
	queriesFile  = "../../grafana-dashboards/test/queries.yml"
	testFile     = "../../grafana-dashboards/test/dashboards_test.yml"
)

// variants are the values a dashboard variable is tested with. Panels using
// the variable get one rule per value, e.g. servers:cpu:a:web_2.
var variants = map[string][]string{
	"server":        {"web-1", "web-2"},
	"load_balancer": {"lb-1", "lb-2"},
}

// testJob is the value of $job in every query; the test data has a second job
// that must never show up.
const testJob = "hetzner"

type dashboard struct {
	Panels []struct {
		Title   string `json:"title"`
		Targets []struct {
			RefID string `json:"refId"`
			Expr  string `json:"expr"`
		} `json:"targets"`
	} `json:"panels"`
}

type rule struct {
	name, base, expr string
}

var (
	nonWord  = regexp.MustCompile(`[^a-z0-9]+`)
	variable = regexp.MustCompile(`\$\{?(\w+)\}?`)
	// A metric selector of the exporter or the promhttp handler.
	selector = regexp.MustCompile(`\b(hetzner_cloud_[a-z0-9_]+|promhttp_[a-z_]+)(\{[^}]*\})?`)
)

func slug(s string) string {
	return strings.Trim(nonWord.ReplaceAllString(strings.ToLower(s), "_"), "_")
}

// rules returns one recording rule per panel query (and per variant).
func rules(t *testing.T) []rule {
	t.Helper()
	files, err := filepath.Glob(filepath.Join(dashboardDir, "grafana_*_dashboard.json"))
	if err != nil || len(files) == 0 {
		t.Fatalf("no dashboards found: %v", err)
	}
	var out []rule
	seen := map[string]bool{}
	for _, file := range files {
		data, err := os.ReadFile(file)
		if err != nil {
			t.Fatal(err)
		}
		var d dashboard
		if err := json.Unmarshal(data, &d); err != nil {
			t.Fatalf("%s: %v", file, err)
		}
		board := strings.TrimSuffix(strings.TrimPrefix(filepath.Base(file), "grafana_"), "_dashboard.json")
		for _, p := range d.Panels {
			for _, target := range p.Targets {
				if target.Expr == "" {
					continue
				}
				base := fmt.Sprintf("%s:%s:%s", board, slug(p.Title), strings.ToLower(target.RefID))
				if seen[base] {
					t.Fatalf("%s: two panels named %q with refId %s; rule names must be unique", file, p.Title, target.RefID)
				}
				seen[base] = true
				out = append(out, expand(base, target.Expr)...)
			}
		}
	}
	return out
}

// expand replaces the dashboard variables, one rule per variant.
func expand(base, expr string) []rule {
	expr = strings.ReplaceAll(expr, "$job", testJob)
	for name, values := range variants {
		if !strings.Contains(expr, "$"+name) {
			continue
		}
		var out []rule
		for _, v := range values {
			out = append(out, rule{
				name: base + ":" + slug(v),
				base: base,
				expr: strings.ReplaceAll(expr, "$"+name, v),
			})
		}
		return out
	}
	return []rule{{name: base, base: base, expr: expr}}
}

func render(rs []rule) string {
	var b strings.Builder
	b.WriteString("# Generated by `go test ./internal/dashboards -update` from grafana-dashboards/*.json.\n")
	b.WriteString("# Every panel query as a recording rule; tested in dashboards_test.yml. Don't edit.\n")
	b.WriteString("groups:\n  - name: dashboards\n    rules:\n")
	for _, r := range rs {
		expr, _ := json.Marshal(r.expr) // a JSON string is a valid YAML double-quoted string
		fmt.Fprintf(&b, "      - record: %s\n        expr: %s\n", r.name, expr)
	}
	return b.String()
}

func TestQueriesFileUpToDate(t *testing.T) {
	want := render(rules(t))
	if *update {
		if err := os.WriteFile(queriesFile, []byte(want), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	got, err := os.ReadFile(queriesFile)
	if err != nil || string(got) != want {
		t.Fatalf("%s is out of date with the dashboards: run `go test ./internal/dashboards -update` (err: %v)", queriesFile, err)
	}
}

// Every query is checked by at least one test (in one of its variants).
func TestEveryQueryTested(t *testing.T) {
	data, err := os.ReadFile(testFile)
	if err != nil {
		t.Fatal(err)
	}
	tests := string(data)
	var missing []string
	for _, r := range rules(t) {
		used := regexp.MustCompile(regexp.QuoteMeta(r.base) + `(:[a-z0-9_]+)?\b`)
		if !used.MatchString(tests) && !slices.Contains(missing, r.base) {
			missing = append(missing, r.base)
		}
	}
	if len(missing) > 0 {
		t.Errorf("queries without a test in %s:\n  %s", testFile, strings.Join(missing, "\n  "))
	}
}

// Every metric selector is limited to the dashboard's job, so two exporters
// (e.g. two Hetzner projects) never mix, and no variable is left unreplaced.
func TestQueriesScopedToJob(t *testing.T) {
	for _, r := range rules(t) {
		for _, m := range selector.FindAllStringSubmatch(r.expr, -1) {
			if !strings.Contains(m[2], `job="`+testJob+`"`) {
				t.Errorf("%s: selector %s is not limited to the job", r.name, m[0])
			}
		}
		if strings.Contains(r.expr, "__name__=~") && !strings.Contains(r.expr, `job="`+testJob+`", __name__=~`) {
			t.Errorf("%s: __name__ selector is not limited to the job", r.name)
		}
		if m := variable.FindString(strings.ReplaceAll(r.expr, "$1", "")); m != "" {
			t.Errorf("%s: unknown dashboard variable %s", r.name, m)
		}
	}
}
